spring:
  jackson:
    mapper:
      use-std-bean-naming: true
  h2:
    console:
      path: /api/db
      enabled: true
  datasource:
    url: jdbc:h2:file:./jms-ui;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api
      default-page-size: 10
  quartz:
    job-store-type: JDBC