spring:
server:  port: 80
  jackson:
    mapper:
      use-std-bean-naming: true    serialization:      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      path: /api/db
      enabled: true
  datasource:
    url: jdbc:h2:file:./jms-ui;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    properties:
      hibernate.enable_lazy_load_no_trans: false
  data:
    rest:
      base-path: /api
      default-page-size: 25
  quartz:
    job-store-type: JDBC
    jms-ui:  embedded:    activemq: 
      enabled: true
      port: 61616