name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
      run: mvn -B package --file pom.xml
